reader:
  #type: keyboardReader or comPortReader
  type : keyboardReader
  com : 1
  exit-barcode : quit
spring:
  datasource:
    url : jdbc:firebirdsql://192.168.1.44:3050/C:\Database\Scanner_test_base.fdb
    password: masterkey
    username: SYSDBA
  main:
    allow-bean-definition-overriding : true
    banner-mode: off
#logging:
#  level:
#    root: off
server:
  port: 80