production: sp
#production: main
reader:
  type: keyboardReader
#  type : comPortReader
  com: 0
  exit-barcode: quit
  main:
    allow-bean-definition-overriding: true
    banner-mode: off

server:
  port: 80

#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#    sql: debug
#    root: off


spring:
  datasource:
    url: "jdbc:firebirdsql://192.168.1.244:3050/c:/OK/22.fdb"
    password: masterkey
    username: SYSDBA
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
